### ISSUE TITLE
Not able to configure Personal Access Token with Secret

### ISSUE THREAD

**Issue by yash982000** [TeamTigers/minisauras#32]
Hello, I have tried to configure as per the steps provided but was not been able to find out what is wrong.

I am a bit confused about the steps that how to use the personal access token with the encrypted secrets.

Please help. 

@shunjid @zubayerhimel @fahad1997 @jinnatul @abusufianshibli

**Comment by yash982000** [comment]
To be precise, I am confused about where to provide the personal access token name and where to put the secret token.

**Comment by hrittikhere** [comment]
Did you go through [this](https://docs.github.com/en/actions/reference/encrypted-secrets)?

**Comment by Teamtigers256** [comment]
Hello @yash982000,

Sorry for the late reply.

You have to set up the secret token in the settings of your repository. Please go through this documentation from GitHub: https://docs.github.com/en/actions/reference/encrypted-secrets

Make sure that the secret name is `TOKEN` like the screenshot below.

![Screenshot from 2021-08-20 10-59-00](https://user-images.githubusercontent.com/79932590/130181554-1629aa5b-6be1-4048-a756-99b2c114ce20.png)


Let us know if that helps.

**Comment by yash982000** [comment]
> Did you go through [this](https://docs.github.com/en/actions/reference/encrypted-secrets)?

YES!!

**Comment by yash982000** [comment]
> Hello @yash982000,
> 
> Sorry for the late reply.
> 
> You have to set up the secret token in the settings of your repository. Please go through this documentation from GitHub: https://docs.github.com/en/actions/reference/encrypted-secrets
> 
> Make sure that the secret name is `TOKEN` like the screenshot below.
> 
> ![Screenshot from 2021-08-20 10-59-00](https://user-images.githubusercontent.com/79932590/130181554-1629aa5b-6be1-4048-a756-99b2c114ce20.png)
> 
> Let us know if that helps.

Ok.

Then where do I put the personal access token.

And ,also is something to be put in value?

**Comment by Teamtigers256** [comment]
![Screenshot from 2021-08-20 11-51-48](https://user-images.githubusercontent.com/79932590/130186219-218fb21d-3535-43c1-b33c-50c2c845c984.png)

@yash982000 `TOKEN` should be the name and your personal access token should be the value like the screenshot.

**Comment by yash982000** [comment]
> ![Screenshot from 2021-08-20 11-51-48](https://user-images.githubusercontent.com/79932590/130186219-218fb21d-3535-43c1-b33c-50c2c845c984.png)
> 
> @yash982000 `TOKEN` should be the name and your personal access token should be the value like the screenshot.

I tried this but the pull request for minification isn't working yet.

I want to setup a workflow such as on commit it checks for minification.

```
name: minisauras

on: [push]

jobs:
  read:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: minisauras
      uses: TeamTigers/minisauras@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      id: dir
      with:
        directory: './' ## minify all files from root directory
```

What should I write inside "ON" such that it triggers while I commit on that default branch?

Much help appreciated.
